### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Anzic23** [kirovilya/ioBroker.zont#20]
zont.0
2023-01-04 00:03:03.930	info	starting. Version 0.5.4 (non-npm: kirovilya/ioBroker.zont#9cef64854117cce020b65f3220dcecf0847ba91c) in /opt/iobroker/node_modules/iobroker.zont, node: v16.19.0, js-controller: 4.0.24

host.iobroker
2023-01-04 00:03:02.487	info	instance system.adapter.zont.0 started with pid 3641198

host.iobroker
2023-01-04 00:03:01.667	info	instance system.adapter.broadlink2.0 started with pid 3641187

host.iobroker
2023-01-04 00:03:00.632	info	Restart adapter system.adapter.broadlink2.0 because enabled

host.iobroker
2023-01-04 00:03:00.632	info	instance system.adapter.broadlink2.0 scheduled normal terminated and will be restarted on schedule.

admin.0
2023-01-04 00:02:38.902	info	==> Connected system.user.admin from ::ffff:172.23.0.1

host.iobroker
2023-01-04 00:02:32.460	info	Restart adapter system.adapter.zont.0 because enabled

host.iobroker
2023-01-04 00:02:32.459	error	instance system.adapter.zont.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

zont.0
2023-01-04 00:02:31.825	info	State value to set for "zont.0.T100_197538.fail" has to be type "string" but received type "boolean"

zont.0
2023-01-04 00:02:31.824	info	State value to set for "zont.0.T100_197538.power" has to be type "string" but received type "boolean"

zont.0
2023-01-04 00:02:31.818	info	State value to set for "zont.0.T100_71114.fail" has to be type "string" but received type "boolean"

zont.0
2023-01-04 00:02:31.817	info	State value to set for "zont.0.T100_71114.power" has to be type "string" but received type "boolean"

zont.0
2023-01-04 00:02:31.802	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

zont.0
2023-01-04 00:02:31.802	info	terminating

zont.0
2023-01-04 00:02:31.801	info	cleaned everything up...

zont.0
2023-01-04 00:02:31.799	error	The state contains the forbidden properties no_adapter_connection, no_boiler_connection, event_connection_lost, boiler_fail, event_boiler_fail, no_valid_params!

zont.0
2023-01-04 00:02:31.799	error	Error: The state contains the forbidden properties no_adapter_connection, no_boiler_connection, event_connection_lost, boiler_fail, event_boiler_fail, no_valid_params! at validateSetStateObjectArgument (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5675:23) at Adapter.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5758:21) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zont/main.js:415:25) at processImmediate (node:internal/timers:468:21)

zont.0
2023-01-04 00:02:31.797	error	unhandled promise rejection: The state contains the forbidden properties no_adapter_connection, no_boiler_connection, event_connection_lost, boiler_fail, event_boiler_fail, no_valid_params!

zont.0
2023-01-04 00:02:31.797	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

zont.0
2023-01-04 00:02:31.514	warn	This object will not be created in future versions. Please report this to the developer.

zont.0
2023-01-04 00:02:31.514	warn	Object zont.0.CLIMATIC_242693.thermostat_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"

zont.0
2023-01-04 00:02:31.513	warn	This object will not be created in future versions. Please report this to the developer.

zont.0
2023-01-04 00:02:31.513	warn	Object zont.0.CLIMATIC_230068.thermostat_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"

zont.0
2023-01-04 00:02:31.511	warn	This object will not be created in future versions. Please report this to the developer.

zont.0
2023-01-04 00:02:31.511	warn	Object zont.0.T100_197538.thermostat_ext_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"

zont.0
2023-01-04 00:02:31.510	warn	This object will not be created in future versions. Please report this to the developer.

zont.0
2023-01-04 00:02:31.510	warn	Object zont.0.SMART20_PRO_285660.thermostat_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"

zont.0
2023-01-04 00:02:31.509	warn	This object will not be created in future versions. Please report this to the developer.

zont.0
2023-01-04 00:02:31.509	warn	Object zont.0.ZTC-720_84280.auto_ignition_state is invalid: obj.common.states has an invalid type! Expected "object", received "string"

zont.0
2023-01-04 00:02:31.508	warn	This object will not be created in future versions. Please report this to the developer.

zont.0
2023-01-04 00:02:31.508	warn	Object zont.0.ZTC-720_84280.auto_ignition is invalid: obj.common.states has an invalid type! Expected "object", received "string"

zont.0
2023-01-04 00:02:31.507	warn	This object will not be created in future versions. Please report this to the developer.

zont.0
2023-01-04 00:02:31.506	warn	Object zont.0.T100_71114.thermostat_ext_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"

zont.0
2023-01-04 00:02:31.489	info	{"temperature":28.6,"humidity":null,"battery":3.2,"rssi":-71.5,"state_time":1672779209,"state_flags":0,"sensor_ok":true}

zont.0
2023-01-04 00:02:31.489	info	{"temperature":19.9,"humidity":null,"battery":3.3,"rssi":-61,"state_time":1672779524,"state_flags":0,"sensor_ok":true}

zont.0
2023-01-04 00:02:30.300	info	config username: Anzic

zont.0
2023-01-04 00:02:30.278	info	starting. Version 0.5.4 (non-npm: kirovilya/ioBroker.zont#9cef64854117cce020b65f3220dcecf0847ba91c) in /opt/iobroker/node_modules/iobroker.zont, node: v16.19.0, js-controller: 4.0.24

**Comment by Anzic23** [comment]
основное тут вот это похоже:


zont.0 | 2023-01-05 00:06:33.659 | error | The state contains the forbidden properties no_adapter_connection, no_boiler_connection, event_connection_lost, boiler_fail, event_boiler_fail, no_valid_params!
-- | -- | -- | --
zont.0 | 2023-01-05 00:06:33.659 | error | Error: The state contains the forbidden properties no_adapter_connection, no_boiler_connection, event_connection_lost, boiler_fail, event_boiler_fail, no_valid_params! at validateSetStateObjectArgument (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5675:23) at Adapter.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5758:21) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zont/main.js:415:25) at processImmediate (node:internal/timers:468:21)
zont.0 | 2023-01-05 00:06:33.655 | error | unhandled promise rejection: The state contains the forbidden properties no_adapter_connection, no_boiler_connection, event_connection_lost, boiler_fail, event_boiler_fail, no_valid_params!
zont.0 | 2023-01-05 00:06:33.654 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

При чем, началось после того, как я добавил себе несколько новых установок. По-моему, после climatic началось. Если нужны логи в дебаг режиме - скажи, вышлю.
